### ISSUE TITLE
Nach Update auf  6.2.8-0ubuntu0 Probleme beim import_workstation

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster/linuxmuster-base#47]
import_workstation beendet sich mit Fehler:

ln: Die symbolische Verknüpfung »/var/linbo/boot/grub/hostcfg/n006-pc01.cfg“ konnte nicht angelegt werden: Datei oder Verzeichnis nicht gefunden

Ursache das Verzeichnis hostcfg existiert nicht auf meinem System.
lmn 6.2 (gewachsenes System von openlml 5)

**Comment by HappyBasher** [comment]
Fixed in https://github.com/linuxmuster/linuxmuster-base/tree/6.2.8-2.
