### ISSUE TITLE
grub disknr on efi/gpt partitions

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-base#48]
Grub starts disks with no. 1 on disks with gpt partition label. So first disk is hd1 and not hd0 as used with msdos partition labels. This should be fixed on workstations import.

**Comment by fschuett** [comment]
Hi, Thomas, maybe this information is helpfull:
I have one single netbook type, where kernel 4.10-rc7 detects mmcblk1 instead of mmcblk0.
All other types of netbooks with gpt partitions appear as (hd0) mmcblk0 in device.map and in linbo.
This is with grub 2.02.
At which point does hd1 appear?

**Comment by HappyBasher** [comment]
Already fixed.
